### ISSUE TITLE
Argument of type 'string' is not assignable to parameter of type 'number | undefined'

### ISSUE THREAD

**Issue by alirealasad** [JamesBroadberry/deno-bcrypt#1]
hi, I was trying this library but I am getting this error. how can I solve this?

error: TS2345 [ERROR]: Argument of type 'string' is not assignable to parameter of type 'number | undefined'.
const hash = await bcrypt.hash("test", salt);

```
import * as bcrypt from "https://deno.land/x/bcrypt/mod.ts";

const salt = await bcrypt.genSalt(8);
const hash = await bcrypt.hash("test", salt);

console.log(hash);
```

**Comment by JamesBroadberry** [comment]
It looks like there's a bug with the types used in new async methods introduced.
For now, you can leave the salt undefined and it'll be auto-generated which is recommended anyway.

I'll get the fix out soon and you can then either specify the new version when importing it or use --reload when running your script to continue using the latest.

Thanks for raising the issue 👍

**Comment by JamesBroadberry** [comment]
I've implemented this fix - please use the --reload flag when running and feel free to re-open this if you're still having problems! 👍
