### ISSUE TITLE
Import fails in Deno v1.7.x

### ISSUE THREAD

**Issue by Schoude** [JamesBroadberry/deno-bcrypt#13]
**Version Info:**
```
deno 1.7.4 (release, x86_64-pc-windows-msvc)
v8 9.0.123
typescript 4.1.4
```

I tried importing the module in Deno v1.7.3/v1.7.4 but I get this error.

```
> const bcrypt = await import("https://deno.land/x/bcrypt@v0.2.4/mod.ts")
Check https://deno.land/x/bcrypt@v0.2.4/mod.ts
Uncaught TypeError: TS2345 [ERROR]: Argument of type '{ type: "module"; deno: boolean; }' is not assignable to parameter of type 'WorkerOptions'.
  Object literal may only specify known properties, and 'deno' does not exist in type 'WorkerOptions'.
    { type: "module", deno: true },
                      ~~~~~~~~~~
    at https://deno.land/x/bcrypt@v0.2.4/src/main.ts:18:23

TS2345 [ERROR]: Argument of type '{ type: "module"; deno: boolean; }' is not assignable to parameter of type 'WorkerOptions'.
  Object literal may only specify known properties, and 'deno' does not exist in type 'WorkerOptions'.
    { type: "module", deno: true },
                      ~~~~~~~~~~
    at https://deno.land/x/bcrypt@v0.2.4/src/main.ts:50:23

TS2345 [ERROR]: Argument of type '{ type: "module"; deno: boolean; }' is not assignable to parameter of type 'WorkerOptions'.
  Object literal may only specify known properties, and 'deno' does not exist in type 'WorkerOptions'.
    { type: "module", deno: true },
                      ~~~~~~~~~~
    at https://deno.land/x/bcrypt@v0.2.4/src/main.ts:83:23
```

This also occurs when importing into a module and not only in the Deno REPL.

Maybe you can look into it thanks!

**Comment by ilsubyeega** [comment]
add `--unstable` flag to deno
references: 
https://github.com/denoland/deno/blob/master/docs/runtime/workers.md -> https://github.com/denoland/deno/blob/bc7817e1610faf0abe3c8629fc8163fdcb36b75f/docs/runtime/stability.md

**Comment by Schoude** [comment]
Above solution works! @ilsubyeega 알려줘셔서 감사합니다. 😄

**Comment by ilsubyeega** [comment]
> Above solution works! @ilsubyeega 알려줘셔서 감사합니다. 😄

maybe i would like to reopen this before owner looked this

**Comment by JamesBroadberry** [comment]
Sorry I forgot to reply earlier, I missed the initial notification!

Glad it's sorted and thanks for stepping in! @ilsubyeega

It's also noted in the readme that you'll need the `--unstable` flag when using async methods but is easy to miss.

**Comment by Ivan-Kouznetsov** [comment]
> It's also noted in the readme that you'll need the --unstable flag when using async methods but is easy to miss.

This error happens when you import the library irrespective of whether you use Async methods
