### ISSUE TITLE
deno-bcrypt leads to Uncaught (in promise) Error:Unhandled error event reached main worker

### ISSUE THREAD

**Issue by finlaydotb** [JamesBroadberry/deno-bcrypt#15]
I introduced deno-bcrypt into an application I am building, as soon as I do, I start getting this error:

 
```
error: Uncaught (in worker "") TS2304 [ERROR]: Cannot find name 'window'.
  let binaryString = window.atob(b);
                     ~~~~~~
    at https://deno.land/x/god_crypto@v1.4.9/src/helper.ts:60:22
error: Uncaught (in promise) Error: Unhandled error event reached main worker.
    at Worker.#poll (deno:runtime/js/11_workers.js:269:21)
```

This error starts popping up on just adding the dependencies without even using it.

```
export {create} from "https://deno.land/x/djwt@v2.2/mod.ts";
```

Any ideas on how to debug this? Not sure if it matters, but my application has some logic that already uses workers

**Comment by finlaydotb** [comment]
Maybe related to this? https://stackoverflow.com/questions/62231656/deno-web-workers-cannot-find-name-window

**Comment by JamesBroadberry** [comment]
Hi,

I'm not sure this is related to deno-bcrypt - it looks like an error related to something in another module called "god_crypto" or "djwt".

If you think this module "bcrypt" is causing the issue, can you create something I can try and replicate please?

Thanks,
James

**Comment by finlaydotb** [comment]
This issue has nothing to do with deno-bcrypt. It is most likely being caused by another dependency but definitely not deno-bcrypt. Sorry for the bother. Closing!
