### ISSUE TITLE
Error just importing

### ISSUE THREAD

**Issue by stillalivx** [JamesBroadberry/deno-bcrypt#16]
I just import the module and it throw me this error:
```
error: TS2345 [ERROR]: Argument of type '{ type: "module"; deno: boolean; }' is not assignable to parameter of type 'WorkerOptions'.
  Object literal may only specify known properties, and 'deno' does not exist in type 'WorkerOptions'.
    { type: "module", deno: true },
```

**Comment by JamesBroadberry** [comment]
Have you used the `--allow-net` and `--unstable` flags when running your application?

**Comment by stillalivx** [comment]
Thanks for respond! 
Yeah, that was my error. I didn't want to use ```--unstable``` flag so I thought that was an issue of old deno versions. Let me delete my pull request. 
Thanks again!

**Comment by JamesBroadberry** [comment]
No problem. Yeah, it's something that you need to unfortunately do (still!) when using the crypto module in WebWorkers, which this module requires to run async. Glad it's all sorted 👍
