### ISSUE TITLE
Async Worker without --allow-net=deno.land

### ISSUE THREAD

**Issue by lcoronelp** [JamesBroadberry/deno-bcrypt#21]
Im working with Async bcrypt but always need the `--allow-net` option with "deno.land" even when i save in cache the dependencies (explicitly i run `deno cache --unstable https://deno.land/x/bcrypt@v0.2.4/src/worker.ts` previously trying to force the cache)

Have some option to avoid the call to "deno.land" in execution time and use the cache? Or i'm missing something?

I think in:
- Apps without internet access
- Developments where can't use "deno.land" in `--allow-net` option by security reasons in execution time
- Because 'deno.land' will be down at these time.

Thanks for your support!

**Comment by Anstroy** [comment]
Hi,

Do you have your Deno updated to the latest?

**Comment by itohatweb** [comment]
You should not have any problems after #20 has been merged. Since this PR removes every dependency.
