### ISSUE TITLE
deno.land/x/bcrypt@v0.3.0 is 404

### ISSUE THREAD

**Issue by timpeq** [JamesBroadberry/deno-bcrypt#25]
It appears that https://deno.land/x/bcrypt@v0.3.0/mod.ts is not available.

Navigating to the site shows '404 - Not Found This version does not exist for this module.' and importing gives the error "Module not found".

I've been able to successfully import from https://raw.githubusercontent.com/JamesBroadberry/deno-bcrypt/master/ instead for now (but that's bad practice in at least one way I'm sure)

**Comment by JamesBroadberry** [comment]
Hey, 

Thanks for raising the issue and letting me know. Looks like deno.land actually changed the way that third party modules work and now require a webhook  to be set up (which I've now done).

It shouldn't 404 any longer.

Thanks again!
James
