### ISSUE TITLE
TS Compiler Issues

### ISSUE THREAD

**Issue by ebebbington** [JamesBroadberry/deno-bcrypt#3]
Getting TypeScript compiler issues when running a Deno app that imports bcrypt. I can work on a PR if you don't have the time

Also I'm not sure what Deno version you are using but i think they information should be added to the `README`, i'm currently running Deno v1.0.1 but seems like it would error regardless of version due to missing types

Is there also a specific version we can import instead of the master branch each time?

```
error TS2339: Property 'crypto' does not exist on type 'typeof globalThis'.
► https://deno.land/x/bcrypt/bcrypt/bcrypt.ts:4:33
     let crypto: Crypto = globalThis.crypto;

error TS2345: Argument of type '{ type: "module"; deno: boolean; }' is not assignable to parameter of type '{ type?: "classic" | "module" | undefined; name?: string | undefined; }'.
Object literal may only specify known properties, and 'deno' does not exist in type '{ type?: "classic" | "module" | undefined; name?: string | undefined; }'.
► https://deno.land/x/bcrypt/main.ts:18:23
     { type: "module", deno: true },

error TS7006: Parameter 'event' implicitly has an 'any' type.
► https://deno.land/x/bcrypt/main.ts:30:25
worker.onmessage = (event) => {

error TS2345: Argument of type '{ type: "module"; deno: boolean; }' is not assignable to parameter of type '{ type?: "classic" | "module" | undefined; name?: string | undefined; }'.
Object literal may only specify known properties, and 'deno' does not exist in type '{ type?: "classic" | "module" | undefined; name?: string | undefined; }'.
► https://deno.land/x/bcrypt/main.ts:50:23
{ type: "module", deno: true },

error TS7006: Parameter 'event' implicitly has an 'any' type.
► https://deno.land/x/bcrypt/main.ts:61:25
worker.onmessage = (event) => {

error TS2345: Argument of type '{ type: "module"; deno: boolean; }' is not assignable to parameter of type '{ type?: "classic" | "module" | undefined; name?: string | undefined; }'.
Object literal may only specify known properties, and 'deno' does not exist in type '{ type?: "classic" | "module" | undefined; name?: string | undefined; }'.
► https://deno.land/x/bcrypt/main.ts:83:23
{ type: "module", deno: true },

error TS7006: Parameter 'event' implicitly has an 'any' type.
► https://deno.land/x/bcrypt/main.ts:95:25
worker.onmessage = (event) => {
```

**Comment by JamesBroadberry** [comment]
Hi,

Thanks for raising the issue, great suggestions. 

I'll upgrade my version of Deno and try to replicate the issues you're having. Are you using the - - unstable flag when running your code? 

You can use any of the releases like so:
```ts
import * as bcrypt from "https://deno.land/x/bcrypt@v0.2.1/mod.ts";
```

I'll have a look later this evening and let you know if I can't replicate it. 

Thanks!

**Comment by ebebbington** [comment]
Cheers for the fast response, and no i'm not using the --unstable flag, guessing it's required? What parts are the unstable features?

**Comment by JamesBroadberry** [comment]
No problem 🙂

The unstable flag is required when using the async methods because the 'crypto' has only recently been added in workers. See https://github.com/denoland/deno/pull/5121

I'm not sure if that's no longer required in Deno 1.0.1 but I'll check that when I'm at my computer later.

**Comment by JamesBroadberry** [comment]
Also, to see which versions you can use, you can check here: https://github.com/JamesBroadberry/deno-bcrypt/releases

**Comment by ebebbington** [comment]
Ah ok cool, fair enough then :) How do I go about adding the `--unstable` flag...? (noob question), tried searching online but nothing worked for me (most likely user error on my end as i've only just heard of that flag)

And thanks for the extra version info, my bad, I obviously don't understand releases well enough :P

Great job on the repo btw, been looking for this exact functionality for a while to implement register/login functionality :P

**Comment by JamesBroadberry** [comment]
You'd place it next to the other flags like this:
deno run --allow-net --unstable file.ts

No problem, I must admit I'm new to it all too.

Thanks you 🙂 I was thinking about what I'd need to build that and noticed Deno didn't have one so had a go at doing it.

Let me know if the unstable flag works for you. Hopefully shouldn't need it in future versions of Deno.

**Comment by JamesBroadberry** [comment]
Hi @ebebbington, I've tried to replicate your issue but can't seem to do so. Could you share the code you're running and what commands you're using to get that to happen please?

**Comment by ebebbington** [comment]
Well.. turns out I forgot to upgrade the deno version, my bad :P Running it in a docker container and haven't had the time to upgrade it - well i've updated it to Deno v1.0.1 but i'll just test it on my host for the time being

**Deno Version**
```
$ deno --version
deno 1.0.1
v8 8.4.300
typescript 3.9.2
```

**Command to run**
```
deno run --allow-net --allow-read --unstable app.ts
```

**Output**
```
Download https://deno.land/x/bcrypt@v0.2.1/mod.ts
error:  // same result without the unstable flag too
```

**Contents of `deps.ts`**
```
export { Drash } from "https://deno.land/x/drash@v0.41.1/mod.ts";

export { Client as PostgresClient } from "https://deno.land/x/postgres@v0.3.9/mod.ts";

import * as bcrypt from "https://deno.land/x/bcrypt@v0.2.1/mod.ts"
export { bcrypt }
```

**Comment by JamesBroadberry** [comment]
Hi,

So I've just tried your code from a blank project, reloaded the module cache and I've removed Drash (to make it easier for me to replicate) and got the following.
I also noticed the typo of "brcypt" should be "bcrypt" in your usage example and change it so it's correct.

**Contents of `deps.ts`**
```ts
import * as bcrypt from "https://deno.land/x/bcrypt@v0.2.1/mod.ts";
export { bcrypt };
```
**Contents of `main.ts`**
```ts
import { bcrypt } from "./deps.ts";

let check = async function (password: string, hash: string) {
  return await bcrypt.compare(password, hash);
};

let res = await check("test", "test");
console.log(res);
```

**Command I ran**
`deno run --allow-net --allow-read --unstable main.ts`

And everything seemed to work as expected.
Are you still running in to issues?

**Comment by ebebbington** [comment]
Yeah your example works fine if in a separate file and only that script is called - can't be related to your module and must be some odd different issue

Deno gave a super helpful message... though this seems to be an issue anyways, other people encounter the issue of no error message

I'll delve deeper into it but i don't think it's a problem qith bcrypt now :)

**Comment by ebebbington** [comment]
Can confirm after upgrading deno to v1.0.2 that the error message is not related to brcrypt

Thanks for all the help though! 💯

**Comment by JamesBroadberry** [comment]
Perfect, just for clarification though, I've had it working on previous versions of Deno so could have been something unrelated too. Thanks for raising the issue anyway! 👍
