### ISSUE TITLE
Add test to catch #27 in the future

### ISSUE THREAD

**Issue by ChristianSiegert** [JamesBroadberry/deno-bcrypt#30]
[Release 0.4.0](https://github.com/JamesBroadberry/deno-bcrypt/compare/v0.3.0...v0.4.0) does not contain a test for #27 to catch a possible regression in the future. I wrote a test for my project but would prefer if you could add it to the deno-bcrypt project (or pass it on to the Deno project if more applicable). The idea is to manually generate a hash once and assert that `await compare(plaintext, oldHash)` still returns true in newly released versions of Deno and bcrypt. If you run the test with Deno 1.22.3 it correctly passes, if you run it with Deno 1.23.0 it correctly fails as it detects the bug.

```ts
// test.ts
import { assertEquals } from "https://deno.land/std@0.143.0/testing/asserts.ts";
import { compare } from "https://deno.land/x/bcrypt@v0.3.0/mod.ts";

Deno.test(compare.name, async () => {
  // Assert that hash generated with older Deno and bcrypt version is still 
  // recognized as valid by newer versions of Deno and bcrypt
  assertEquals(
    await compare(
      "password123",
      "$2a$10$i7yVylH68UTYSoa./.BWxO0NTXjvPRMzT6F0CgKItqKUqwQwj3y0W",
    ),
    true,
  );
});
```

**Comment by JamesBroadberry** [comment]
Hi, I've added the test you've suggested, sorry it's taken a while to do! Thanks for the suggestion.
