### ISSUE TITLE
[Question] Why does `bcrypt.compare` return if the bytestring length are unequal?

### ISSUE THREAD

**Issue by keysmusician** [JamesBroadberry/deno-bcrypt#33]
I'm just wondering why `bcrypt.compare` returns if the hash lengths are unequal before doing the individual byte comparison, and if that makes it susceptible to timing attacks.

```
  if (hashed_bytes.length !== try_bytes.length) return false;
```

**Comment by JamesBroadberry** [comment]
Honestly, I'm not too sure. This code was originally just ported from jBCrypt, where the original source for the code you're referring to is [here](https://github.com/jeremyh/jBCrypt/blob/e015c2c110ab7cf544400893f3543b45f359ff58/src/main/java/org/mindrot/BCrypt.java#L771). I'm not a security expert so just wrote the code to have as much parity with the existing library as possible.

The code below the check assumes that both arrays are the same length to be able to compare the byte arrays, so I imagine it's to guard against that.

**Comment by keysmusician** [comment]
I see. I'm not too knowledgeable on security myself. I wonder under what circumstances the hashes might not be equal in length. Presumably entering an incorrect password wouldn't cause that (In which case it should be resilient against timing attacks?). Perhaps if the hashed password was produced with a different algorithm that the one being used for comparison. In that case I guess the only thing a timing attack could glean is a good idea of which hashing algorithm was used. I don't think that shouldn't be a problem

**Comment by JamesBroadberry** [comment]
I assume that the bytes are always a constant length and this is just a check as a fail-safe to ensure there aren't any out-of-bounds problems during runtime. Feel free to play around with the source code and confirm it, if you like
