### ISSUE TITLE
Version Std Encoding Import

### ISSUE THREAD

**Issue by ebebbington** [JamesBroadberry/deno-bcrypt#5]
It would be nice if you could version the following import on `bcrypt/bcrypt.ts`:
```typescript
import { encode } from "https://deno.land/std/encoding/utf8.ts";
```

To avoid using the master branch and causing any issues for users (should any ever arise)

**Comment by JamesBroadberry** [comment]
Yeah, that's a good idea - I'll add it in. 
Thanks for the suggestion!

**Comment by ebebbington** [comment]
Nice one! While i'm here, really nice work on bcrypt! So glad Deno has this :)

**Comment by JamesBroadberry** [comment]
I've updated the code to reference specific versions of the std modules, let me know if you think there are any issues still 👍 

No problem 😄 I wanted something useful to do using Deno and used bcrypt before in a Node.js project so thought it'd be worth porting over. Glad to hear you're finding it useful!

**Comment by ebebbington** [comment]
Bloody hell that was fast! And I was so happy some ported over bcrypt :P Keep up the great work!
